# Generated by Django 6.0.1 on 2026-03-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
    ]
