# Generated by Django 6.0.1 on 2026-03-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_test_cases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(default='# Write your Python code here\n'),
        ),
    ]
